services:
  - type: web
    name: controle-despesas
    runtime: php
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        value: controle_gastos
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false